import AddRouter from './add/index.js';
import GetRouter from './get/index.js';
import Log from '../../../../tools/logger/index.js';
import type { Router } from 'express';

/**
 * Initialize oidc routes, not generated by oidc middleware.
 * @param router Express router.
 */
export default (router: Router): void => {
  Log.debug('User router', 'Starting router');

  const prefix = '/user';

  router.use(prefix, new AddRouter().router).use(prefix, new GetRouter().router);
};
